### ISSUE TITLE
plumbus doesn't work

### ISSUE THREAD

**Issue by irtaylor** [irtaylor/Capstone_Adventure#31]
Using the plumbus in the prison world prints:
"Morty, we've already done that. We can't be wasting time!"

even if you've never used it. can't get success message to print.

**Comment by smcreamer** [comment]
It seems to be failing on reveal_hidden_items() in rm_room (line 53):
```
def reveal_hidden_items(self):
        """
        Helper method used to transfer all items in the hidden array to that of the public, items array.
        """
        if len(self.hidden_items) > 0:
            while len(self.hidden_items) > 0:
                self.items.append(self.hidden_items.pop())
            return True
        return False
```

Summer's Cell has no hidden items in it, so it prints the already done text "We've already done that" etc.  ~The debate is if we want to throw a phantom item into hidden_item for that room to "fix" it~ (this isn't an option since the "hidden item" will be populated to be visible to the user when the Plumbus is used) or if we want to special code that room file (throw "or self.key=="summers_cell" at the end of the first if-statement of the above function or something).

Kyle will probably have a more elegant solution to propose.
