### ISSUE TITLE
fix command "look <item/feature>"

### ISSUE THREAD

**Issue by kberg721** [irtaylor/Capstone_Adventure#32]
doesn't ignore case

**Comment by smcreamer** [comment]
This appears to just be an issue with Summer in Summer's Cell in Prison World.  This is because in the summers_cell.json file, the key for the feature Summer is erroneously capitalized when all keys are expected to be lower case.  Changing the key to be lower case in the offending file appears to resolve the issue.  

Because this is a tiny fix, I'm unsure if we want to add this into one of your guys' updates instead of adding a new branch.

**Comment by smcreamer** [comment]
Fixed.
